//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cart
{
    public int CartID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<int> ProductQnt { get; set; }
    public Nullable<int> TotalPrice { get; set; }
}

public partial class Category
{
    public int CategoryID { get; set; }
    public string Name { get; set; }
}

public partial class Product
{
    public int ProductID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string Name { get; set; }
    public string Details { get; set; }
    public Nullable<int> Price { get; set; }
    public string ImagePath { get; set; }
}

public partial class User
{
    public int UserID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Pws { get; set; }
}
